.\" Manpage for libui
.\" Please contact fharvell@siteservices.net to correct errors or typos.
.\" Please note that the libui library is young and under active development.
.\"
.\" This content and associated files are published by siteservices.net, Inc.
.\" are marked CCO 1.0. Permission is unconditionally granted to anyone with the
.\" interest the full rights to use, modify, publish, distribute, sublicense,
.\" and/or sell this content and all associated files. To view a copy of CCO
.\" 1.0, visit https://creativecommons.org/publicdomain/zero/1.0/.
.\"
.\" purpose, and noninfringement. In no event shall the authors or publishers be
.\" liable for any claim, damages, or other liability, whether in an action of
.\" contract, tort, or otherwise, arising from, out of, or in connection with
.\" the use of this content or any of the associated files.
.\"
.Dd March 22, 2026
.Dt LIBUI 1
.Os
.Sh NAME
.Nm libui
.Nd Perform
.Xr libui.sh 3
library utility actions
.Sh SYNOPSIS
.Sy libui
.Op Fl c Fl C Fl d Fl D Fl g Fl i Fl I Fl l Fl L Fl m Fl M Fl n Fl N Fl p Fl P Fl s Fl S Fl t Fl T Fl u Fl U Fl v Fl V Fl h Fl H
.Op Fl e Ar <shell> ...
.Op Fl x Ar <test_option>
.Op Fl X Ar <option>
.Op Ar <parameter>
.Sh DESCRIPTION
Used to perform various utility functions for the
.Xr libui.sh 3
user interface library.
The
.Nm
command is also the primary application launcher for scripts that use the
.Xr libui.sh 3
user interface library.
In the loader mode, the
.Nm
command loads the
.Xr libui.sh 3
library and then sources the application script.
.Pp
Some of the primary utility functions are:
.Bl -tag -offset 4n -width 4n
.It Fl c
Create a default
.Xr libui.sh 3
configuration file«
.It Fl C
Reset (clear) the
.Xr libui.sh 3
caches
.It Fl d
Demonstrate some
.Xr libui.sh 3
capabilities«
.It Fl i
Install the
.Xr libui.sh 3
library into the COMMONROOT directory with libui test suite
.It Fl m
Access the
.Xr libui.sh 3
man page«
.It Fl n
Create a new
.Xr libui.sh 3
script from the template
.It Fl s
Display
.Xr libui.sh 3
statistics
.El
.Pp
The
.Nm
script can be executed using the following:
.Bd -ragged -offset 4n
.Sy libui
.Op Fl c Fl C Fl d Fl D Fl g Fl i Fl I Fl l Fl L Fl m Fl M Fl n Fl N Fl p Fl P Fl s Fl S Fl t Fl T Fl u Fl U Fl v Fl V Fl h Fl H
.Op Fl e Ar <shell> ...
.Op Fl x Ar <test_option>
.Op Fl X Ar <option>
.Op Ar <parameter>
.Ed
.Pp
Available command line options are:
.Bl -tag -offset 4n -width 4n
.It Fl c
Config
.Pp
Create a default
.Qq Sy libui.conf
configuration file in the
.Qq Sy .libui
directory in the user's home directory.
.It Fl C
Cache Reset
.Pp
Reset the
.Xr libui.sh 3
Caches.
.Pp
This will reset the
.Xr libui.sh 3
caches.
Currently, only display code caches are created.
The display codes cache for the current display will be regenerated upon the
next
.Xr libui.sh 3
execution.
See the
.Sx FILES
section below for more information.
.It Fl d
Demo
.Pp
Provide a simple
.Xr libui.sh 3
capabilities demonstration.
.It Fl D
Defer
.Pp
Defer the user's local environment by moving files already in the
.Ar <parameter>
directory into a subdirectory named "Deferred".
.Pp
This option moves any file that exist in the user's local environment, i.e., the
directory from which the
.Nm
command has been executed, if the file also exist in the
.Ar <parameter>
directory.
If a
.Ar <parameter>
is not provided, the
.Ev COMMONROOT
environment variable is used.
.It Fl e Ar <shell> ...
Execution Shell
.Pp
Perform regression testing using the provided
.Ar <shell> .
The option can be used more than once to test with multiple shells.
The default is testing with both zsh and bash.
Note: the
.Xr libui.sh 3
library was only designed to work with the Z shell and Bash shells.
.It Fl g
Group
.Pp
Set the permissions on the installed files and directories to be group writable.
.It Fl i
Install (with tests)
.Pp
Install the
.Xr libui.sh 3
utility files along with the with
.Xr libui.sh 3
test suite into the directory specified by
.Ar <parameter> .
If a
.Ar <parameter>
is not provided, the directory specified by the
.Ev COMMONROOT
environment variable is used.
If a parameter is not provided and
.Ev COMMONROOT
is empty, an error will be generated.
.Pp
During installation, the
.Nm
utility will be installed in the bin subdirectory.
The
.Xr libui.sh 3
library files will be installed in the lib/sh subdirectory.
.Xr libui.sh 3
documentation will be installed into the share/doc subdirectory.
The man pages will be installed into the share/man/man1 and share/man/man3
subdirectories.
.It Fl I
Install (without tests)
.Pp
Install the
.Xr libui.sh 3
utility files (without the
.Xr libui.sh 3
test suite) into the directory specified by
.Ar <parameter> .
If a
.Ar <parameter>
is not provided, the directory specified by the
.Ev COMMONROOT
environment variable is used.
.Pp
This is the same installation as performed when using the
.Fl i
(Install) option.
Please see the
.Sx Fl i
(Install) option for more details.
.It Fl l
List
.Pp
List the files that would be included in a
.Xr libui.sh 3
"package".
.It Fl L
(Remove) Lock Files
.Pp
Remove leftover
.Xr libui.sh 3
lock files.
.It Fl m
Man Page
.Pp
Display the
.Xr libui.sh 3
man page.
.It Fl M
Manpath
.Pp
Generate a MANPATH command line that includes the
.Nm
and
.Xr libui.sh 3
man page subdirectory.
The generated manpath command line can be evaluated by the shell using a command
similar to:
.Sy eval Qq Sy libui Fl M
.It Fl n
New Script
.Pp
Creates a new script from the share/doc/libui-template template file at the file
path provided by the
.Ar <parameter> .
The new script will provide the recommended outline of a
.Xr libui.sh 3
script and includes some sample statements (identified as demo content).
.It Fl N
New Script (without demo content)
.Pp
Creates a new script from the share/doc/libui-template template file (without
the demo content) at the file path provided by the
.Ar <parameter> .
.It Fl p
Package
.Pp
Create a
.Xr libui.sh 3
"tar package" at the file path provided by
.Ar <parameter> .
.Pp
This option creates a self-extracting "tar package"
in the file path provided by the
.Ar <parameter>
containing the
.Xr libui.sh 3
files from the current libui source directory.
.It Fl P
Pre-package
.Pp
Update the
.Xr libui.sh 3
files and man page datestamps in preparation for packaging.
.It Fl s
Stats
.Pp
Display the
.Xr libui.sh 3
usage stats.
.Pp
Displays a large set of usage statistics collected about the
.Xr libui.sh 3
usage since the last installation or reset.
This includes overall usage information as well as per-function usage.
.It Fl S
State Reset
.Pp
Reset
.Xr libui.sh 3
state.
.Pp
This will reset the
.Xr libui.sh 3
state.
Currently this includes statistics and the executed command ledger.
A new statistics file and executed command ledger will be recreated and data
collection will restart.
See the
.Sx FILES
section below for more information about the associated files.
.It Fl t
Test
.Pp
Perform a suite of
.Xr libui.sh 3
regression tests.
.It Fl T
(Single) Test
.Pp
Perform a single
.Xr libui.sh 3
regression test.
The name of the test must be provided as the first parameter.
.It Fl u
Update
.Pp
Update
.Xr libui.sh 3
in COMMONROOT.
.Pp
This option updates files in the
.Ar <parameter>
directory with files that exist in the directory from which
.Nm
is being executed.
If a
.Ar <parameter>
is not provided, the directory specified by the
.Ev COMMONROOT
environment variable is used.
.It Fl U
User Reset
.Pp
Reset user information.
.Pp
This will reset (recreate) the stored user information.
The current user information file is removed and the user information questions
will be asked to recreate a new user information file.
See the
.Sx FILES
section below for more information.
.It Fl v
Version
.Pp
Provide version information for both the
.Nm
command and the loaded
.Xr libui.sh 3
mods.
.It Fl V
Verify
.Pp
Verify
.Xr libui.sh 3
in COMMONROOT.
.Pp
This option verifies files in the
.Ar <parameter>
directory with files that exist in the directory containing the
.Xr libui.sh 3
library from which
.Nm
is being executed.
If a
.Ar <parameter>
is not provided, the directory specified by the
.Ev COMMONROOT
environment variable is used.
.Pp
When
.Fl V
is provided twice, displays differences (using diff) between the directories.
.It Fl x
Test Mode Options
.Pp
Only for testing.
Set various test mode options.
The option utilizes various sub-options to support specific tests.
.Xr libui.sh 3 .
.It Op Ar <parameter>
The name of the test to perform, the package filename, or the "COMMONROOT"
directory depending upon the option flags used.
.El
.Ss STANDARD OPTIONS
This script was built using the
.Xr libui.sh 3
user interface library.
Standard command line options provided by the
.Xr libui.sh 3
library are:
.Fl h
or
.Fl H
(Help) and
.Fl X Ar <option>
(XOption).
XOptions include Confirm, Force, NoAction, Overwrite, Quiet, Version, and Yes.
They are enabled using the first letter of the option (lower or upper case) as
.Ar <option> .
Please see
.Xr libui.sh 3
for more information.
.Pp
Note: Option value defaults can be obtained by executing with the
.Fl h
or
.Fl H
(Help) option.
.Sh FILES
When used with the
.Fl c
(Config) option, libui will create a default
.Xr libui.sh 3
configuration file.
The file will be created in the directory pointed to by the
.Ev LIBUI_CONFIG
environment variable.
Unless otherwise defined, the
.Xr libui.sh 3
library will default
.Ev LIBUI_CONFIG
to
.Qq Sy ${XDG_CONFIG_HOME}/libui ,
or if
.Qq Sy ${XDG_CONFIG_HOME}
is not set, then to
.Qq Sy ${HOME}/.config/libui .
The configuration filename is
.Qq Sy libui.conf .
.Pp
When used with the
.Fl i
(Install) option, libui will install the
.Xr libui.sh 3
library, library mods, and
.Nm
library utility will be installed in the
.Qq Sy lib/sh
subdirectory.
Example binaries will be installed in the
.Qq Sy bin
subdirectory.
And man pages will be installed into the
.Qq Sy share/man/man1
and
.Qq Sy share/man/man3
subdirectories.
.Pp
When used with the
.Fl C
(Cache Reset) option, libui will delete the display codes caches.
The display codes caches are stored in the
.Ev LIBUI_CACHE
directory.
The display codes cache filenames are in the form
.Qq Sy display-${TERM} .
.Pp
When used with the
.Fl S
(State Reset) option, libui will delete the statistics files from the
.Ev LIBUI_STATE
directory.
Unless otherwise defined, the
.Xr libui.sh 3
library will default
.Ev LIBUI_STATE
to
.Qq Sy ${XDG_STATE_HOME}/libui ,
If
.Qq Sy ${XDG_STATE_HOME}
is not set, then
.Ev LIBUI_STATE
will default to
.Qq Sy ${HOME}/.local/state .
The statistics file name is
.Qq Sy stats
and the command ledger file name is
.Qq Sy ledger .
.Pp
When used with the
.Fl U
(User Reset) option, libui will reset (recreate) the user information.
The user information is stored in the
.Qq Sy ${XDG_CONFIG_HOME}/user
file, or if
.Qq Sy ${XDG_CONFIG_HOME}
is not set, then to the
.Qq Sy ${HOME}/.config/user
file.
.Pp
The script creates a temporary directory (via GetTmp) that should be removed
upon exit.
Certain circumstances (e.g. some crashes) may prevent the cleanup handler from
being executed leaving the temporary directory in place.
.Sh EXAMPLES
Some example uses include:
.Bd -literal -offset 4n
.Sy libui Fl c
.Ed
.Pp
Create a default
.Xr libui.sh 3
configuration file, overwriting the file if it exists.
.Bd -literal -offset 4n
.Sy libui Fl d
.Ed
.Pp
Provide a simple demonstration of the
.Xr libui.sh 3
user interface library capabilities.
.Bd -literal -offset 4n
.Sy libui Fl i
.Ed
.Pp
Install a
.Xr libui.sh 3
"package" into the directory pointed to by the
.Ev COMMONROOT
environment variable.
The package installs the
.Xr libui.sh 3
library and libui utility into the ${COMMONROOT}//lib/sh directory and
associated man pages into ${COMMONROOT}//man/man1 and ${COMMONROOT}/man//man3
directories.
.Bd -literal -offset 4n
.Sy libui Fl m
.Ed
.Pp
Display this man page.
.Bd -literal -offset 4n
.Sy libui Fl R
.Ed
.Pp
Reset the display codes cache, the statistics file, and the user information
file.
Ask user information questions and save the answers in the user information
file.
.Bd -literal -offset 4n
.Sy libui Fl t
.Ed
.Pp
Perform regression tests on the
.Xr libui.sh 3
user interface library.
.Bd -literal -offset 4n
.Sy libui Fl x Sy d Fl t
.Ed
.Pp
Perform
.Xr libui.sh 3
regression tests with debugging messages.
.Bd -literal -offset 4n
.Sy libui Fl T Sy test_LIBUI
.Ed
.Pp
Perform the single regression test named "test_LIBUI".
.Bd -literal -offset 4n
.Sy libui Fl u
.Ed
.Pp
Updates any of the files in the directory pointed to by the
.Ev COMMONROOT
environment variable with files that exist in the directory containing the
.Xr libui.sh 3
library.
.Bd -literal -offset 4n
.Sy libui Fl U
.Ed
.Pp
Unify with COMMONROOT by removing duplicate
.Xr libui.sh 3
files from ~/.env«
.Bd -literal -offset 4n
.Sy libui Fl v
.Ed
.Pp
Verify the
.Xr libui.sh 3
"package" in the COMMONROOT directory«
Compares files in the directory containing the
.Xr libui.sh 3
library with those in the directory pointed to by the
.Ev COMMONROOT
environment variable.
.Sh SEE ALSO
.Xr libui.sh 3 ,
.Xr libuiConvert.sh 3 ,
.Xr libuiFile.sh 3 ,
.Xr libuiFileRecord.sh 3 ,
.Xr libuiInfo.sh 3 ,
.Xr libuiPackage.sh 3 ,
.Xr libuiSort.sh 3 ,
.Xr libuiSyslog.sh 3 ,
.Xr libuiTimer.sh 3 ,
.Xr libuiUser.sh 3
.Sh AUTHORS
.An F Harvell
.Mt <fharvell@siteservices.net>
.Sh BUGS
No known bugs.
